### ISSUE TITLE
[Request] CIA build

### ISSUE THREAD

**Issue by favna** [ihaveamac/screenshot-merge#1]
Well this is a longshot ihaveamac, but I don't suppose you can make this into a CIA build can you? That would be just totally awesome for us CFW users. Just home button out of the app we just took a NTR screenshot from, run your applet and then ftpd to transfer it for example.

**Comment by ihaveamac** [comment]
I've been meaning to do it for some time, and now that lpp-3ds r5 is out with romfs support, it might be time to do it.

**Comment by ihaveamac** [comment]
the main thing stopping me now is I don't really have a good icon. the current one just uses the default one.

**Comment by favna** [comment]
Heh.. well.... How about smea's icon for his screenshot tool? That being [this](http://i.imgur.com/zFJxlOw.png) (ripped with SMDH creator)

**Comment by favna** [comment]
Otherwise if you give me an idea (because I literally have no inspiration rn) I could give it a shot. I'm pretty well versed with photoshop.

**Comment by ihaveamac** [comment]
I feel like I should have to make some changes to it instead of just copying it entirely.

though I have an idea, you could probably copy the "square" in the icon and put one on top of the other?

**Comment by favna** [comment]
[How about this then](http://i.imgur.com/NMcTaJH.png)?

**Comment by ihaveamac** [comment]
it looks good but it's not 48x48 (52x47)

**Comment by favna** [comment]
Oh didn't know it had to be 48x48. Few mins then. Should be easy enough as I have some green background space left to crop out

**Comment by favna** [comment]
There. now they are 48x48. Uploaded them on MEGA so there shouldn't be any quality loss. Also put both a jpg and a png as I don't know which you need

MEGA folder: https://mega.nz/#F!RRxBwSLR!iR3gZSbjj8j9rXvl65-qxw

**Comment by ihaveamac** [comment]
just a note, GitHub allows file uploading as well. anyway, the png is used by smdhtool/bannertool, so I'll use that. thanks!

**Comment by favna** [comment]
Eh that's just me being nitpicky. When uploading images to github (I know with drag&drop) it uploads them sort of the same way as if I'd do imgur (direct raw image) as opposed to mega/drive/dropbox etc where it's the file rather than the image. Yeah.. very nitpicky =P

(i think anyway.. XD)

**Comment by ihaveamac** [comment]
not exactly inspired for banner...
![hni_0051](https://cloud.githubusercontent.com/assets/590576/13543286/9871101c-e21e-11e5-8791-d630c4f4c3ba.JPG)

**Comment by favna** [comment]
Hm what is the size for a wide banner? I have an idea actually. Basically a green background with the "square" icons on the right and left of it written "screenshot merger" in white.

**Comment by ihaveamac** [comment]
256x128 is what bannertool takes.

**Comment by favna** [comment]
![banner](https://cloud.githubusercontent.com/assets/4019718/13543532/66261eba-e26c-11e5-8a4f-ef179cf208e6.png)
how's this? If ok and you want the raw file i've updated the mega folder. 

Needed some kind of how to say... more distinguishing factor in the green backdrop or it would just look too dull so changed from the icon (which was a bad underlaying image due to the white) to the classic camera shutter.

**Comment by ihaveamac** [comment]
well the program is named "screenshot merge" with no ending r, and the background "camera shutter" isn't centered. (yes these things bug me somewhat >,>) other than that it's good

**Comment by favna** [comment]
![banner](https://cloud.githubusercontent.com/assets/4019718/13543700/084d75a2-e26e-11e5-99f3-e86fdc1d44c5.png)

ahahaha don't worry! I actually didn't notice else I would've centered it. Both the text and the shutter are now centered in relation to the green backdrop (as opposed to the entire image which is 4 pixels wider on each side, but otherwise it would be a sharp edge rectangle instead of a rounded edge one)

Again mega also updated if you want to grab it from there (gotta love that mega sync program)

**Comment by ihaveamac** [comment]
![hni_0052](https://cloud.githubusercontent.com/assets/590576/13544005/bfeba5ec-e225-11e5-992e-c44391d16bee.JPG)

**Comment by favna** [comment]
Only suggestion I'd still have is to change the text in the popup box on the bottom screen to simply say Screenshot Merge if you're cool with that but other than that it looks great imo :+1:

**Comment by ihaveamac** [comment]
I'm not going to include the version in the CIA icon since it doesn't immediately update if you install a newer version (if I ever release a newer one).

**Comment by ihaveamac** [comment]
523ef9a7c319efd7458bddfb8d704028554e6f07

I'll try putting out 1.2 now then
