### ISSUE TITLE
Error when running tool

### ISSUE THREAD

**Issue by zweilous** [ihaveamac/screenshot-merge#2]
Error: [string "?"]:153: attempt to perform arithmetic on a nil value

Multiple screenshots on my SD card root from NTR with "bot_xxxx.bmp" and "top_xxxx.bmp" as file names, using N3DS on version 11.3 with luma & a9lh. It only creates the screenshots-merged folder and its subdirectories.

**Comment by ihaveamac** [comment]
the error relates to an image in the "screenshots" folder (from \*hax). if you only care about the NTR screenshots try renaming this folder to anything else.

**Comment by zweilous** [comment]
i see. thanks
