### ISSUE TITLE
tool causes crash post-sighax installation

### ISSUE THREAD

**Issue by zweilous** [ihaveamac/screenshot-merge#3]
it attempts to merge screenshots then crashes. i've never had this problem before prior to installing boot9strap; works as it should with a9lh. it doesn't create the merged image file properly so it can't be viewed on a pc, but the bmp file exists. i also have a arm11 dump from luma if needed

[scr-merge issue.zip](https://github.com/ihaveamac/screenshot-merge/files/1017720/scr-merge.issue.zip)

**Comment by ihaveamac** [comment]
old issue, something might be wrong with your setup if it still happens. works fine here.
