### ISSUE TITLE
Error: [string "?"]:160: attempt to preform arithmetic on a mil value

### ISSUE THREAD

**Issue by Shadow322** [ihaveamac/screenshot-merge#6]
I am trying to merge SS in the luma/screenshots folder and i have no screenshots in root or any place else on sd card using SSM v1.3

**Comment by ihaveamac** [comment]
did you solve your issue? if so, please post how.

**Comment by ihaveamac** [comment]
"i closed it and it was my over looking at a screenshots folder on the root of my card
renamed it and it worked"

"as my  screenshots folder had ss in it with same name as in my luma/screenshots folder is why i got that error"
