### ISSUE TITLE
No longer work with Luma 9.0 screenshots?

### ISSUE THREAD

**Issue by CodyMKW** [ihaveamac/screenshot-merge#7]
Since screenshots are now sorted by date/time I guess this no longer works right?

**Comment by ihaveamac** [comment]
not without updating it to support the new screenshot format, which i'll probably do eventually

**Comment by piratesephiroth** [comment]
I added my pull request

**Comment by CodyMKW** [comment]
tried it and works great

**Comment by IngeniousDefault** [comment]
Can someone compile the pull request (3dsx version) for me? Thank you!

**Comment by ihaveamac** [comment]
https://github.com/ihaveamac/screenshot-merge/releases/tag/1.4
